### ISSUE TITLE
Dataset download missing

### ISSUE THREAD

**Issue by tobias-liaudat** [louaaron/Reflected-Diffusion#2]
Hi @louaaron 

Thanks for the code and the nice paper. Great work! 

The `dataset` directory you mention in the readme with the helper functions to download the data you used in your paper

```
python download_cifar10.py
sh download_imagenet32.sh
python compile_imagenet64.py /path/to/imagenet/
```

 seems to be missing in the repo. Would it be possible to add it?

**Comment by louaaron** [comment]
Apologies, this was gitignored. Fixed with last push.
